trigger:
  branches:
    include: [main]

pool:
  name: Default 

variables:
  buildConfiguration: 'Release'
  versionSuffix: '$(Build.BuildId)'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    version: '8.0.x'

- script: dotnet restore
  displayName: 'Restore NuGet Packages'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Project'

- script: dotnet pack src/YourClassLibrary/YourClassLibrary.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --version-suffix $(versionSuffix)
  displayName: 'Pack NuGet Package'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'

- task: NuGetCommand@2
  displayName: 'Push NuGet Package'
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishVstsFeed: '<your-feed>'
